
version: '3'

services:
  frontend:
    build: ./client
    ports:
      - "4000:4000"
    networks:
      - n1
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "4001:4001"
    networks:
      - n1
    depends_on:
      - db
  

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - n1

networks:
  n1:
    driver: bridge